// Renders the generated client under `src/generated/` from the committed IDL (never from
// `target/idl/`, whose address CI rewrites to a fresh keypair). Run by `npm run generate`;
// the committed output is regenerated and diffed in CI, so nothing under `src/generated/` is
// ever edited by hand. Codama 1.11.0, nodes-from-anchor 1.5.6, renderers-js 2.5.0, pinned.
import { readFileSync, writeFileSync } from "node:fs";

import { rootNodeFromAnchor } from "@codama/nodes-from-anchor";
import { renderVisitor } from "@codama/renderers-js";
import {
  accountValueNode,
  addPdasVisitor,
  constantPdaSeedNodeFromString,
  createFromRoot,
  deleteNodesVisitor,
  pdaLinkNode,
  pdaSeedValueNode,
  pdaValueNode,
  programIdValueNode,
  setInstructionAccountDefaultValuesVisitor,
  updateInstructionsVisitor,
} from "codama";

const idl = JSON.parse(readFileSync(new URL("../../idl/mybarpool.json", import.meta.url), "utf8"));
const codama = createFromRoot(rootNodeFromAnchor(idl));

// `create_pool` names the override seed `creator` where `buy` names it `wallet`; the seeds are
// the same bytes (PROGRAM §3.6), so the duplicate PDA the importer invents is pointed back at
// the one `walletOverride` PDA and deleted.
codama.update(
  updateInstructionsVisitor({
    createPool: {
      accounts: {
        walletOverride: {
          defaultValue: pdaValueNode(pdaLinkNode("walletOverride"), [
            pdaSeedValueNode("wallet", accountValueNode("creator")),
          ]),
        },
      },
    },
  }),
);
codama.update(deleteNodesVisitor(["[pdaNode]createPoolWalletOverride"]));

// Anchor's event authority (PROGRAM §7) and the program's own address are the same on every
// emitting instruction; the IDL does not mark them as PDAs, so they are added here.
codama.update(
  addPdasVisitor({
    mybarpool: [
      { name: "eventAuthority", seeds: [constantPdaSeedNodeFromString("utf8", "__event_authority")] },
    ],
  }),
);
codama.update(
  setInstructionAccountDefaultValuesVisitor([
    { account: "eventAuthority", defaultValue: pdaValueNode("eventAuthority") },
    { account: "program", defaultValue: programIdValueNode() },
  ]),
);

// The renderer takes the package folder and writes under its `src/generated/` (deleting it
// first); it returns a promise, awaited so the extra file below lands after the rewrite.
const pkg = new URL(".", import.meta.url).pathname;
const out = `${pkg}src/generated/`;
await codama.accept(
  renderVisitor(pkg, {
    kitImportStrategy: "rootOnly",
    importExtension: "js",
    syncPackageJson: false,
    formatCode: true,
    deleteFolderBeforeRendering: true,
  }),
);

// The renderer's `getMybarpoolErrorMessage` returns a placeholder in production bundles and
// names nothing; the chain layer maps a code to its IDL name through this table instead.
const names = idl.errors.map((e) => `  ${e.code}: "${e.name}",`).join("\n");
writeFileSync(
  `${out}errorNames.ts`,
  `/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

/** PROGRAM §8 error code → name, from the committed IDL. */
export const MYBARPOOL_ERROR_NAMES: Readonly<Record<number, string>> = Object.freeze({
${names}
});
`,
);
console.log(`rendered ${out} from idl/mybarpool.json (${idl.instructions.length} instructions)`);
