//! The axis shuffle, PROGRAM §6.2, against the shared vector files and as
//! properties over the 1,000 bulk values. The files are generated by
//! `packages/shared/test/vectors.test.ts` and committed; the program must
//! reproduce them exactly.

use std::path::PathBuf;

use mybarpool::axes::{axis, draw_axes};
use mybarpool::constants::{AXIS_LABEL_AWAY, AXIS_LABEL_HOME, VAR_REPLACEMENTS_MAX};
use serde::Deserialize;

fn vectors_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../packages/shared/src/vectors")
}

fn load(file: &str) -> Vec<AxesEntry> {
    let path = vectors_dir().join(file);
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    let file: File =
        serde_json::from_str(&text).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    file.entries
}

fn hex32(s: &str) -> [u8; 32] {
    assert_eq!(s.len(), 64);
    let mut out = [0u8; 32];
    for (i, b) in out.iter_mut().enumerate() {
        *b = u8::from_str_radix(&s[2 * i..2 * i + 2], 16).expect("hex");
    }
    out
}

#[derive(Deserialize)]
struct File {
    entries: Vec<AxesEntry>,
}

#[derive(Deserialize)]
struct AxesEntry {
    value: String,
    home: [u8; 10],
    away: [u8; 10],
}

fn is_permutation(a: &[u8; 10]) -> bool {
    let mut sorted = *a;
    sorted.sort_unstable();
    sorted == [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
}

#[test]
fn axes_json_matches_for_every_entry() {
    // PROGRAM §6.2; BUILD-PLAN acceptance "axes match the reference implementation".
    let entries = load("axes.json");
    assert_eq!(entries.len(), 24);
    for e in &entries {
        let value = hex32(&e.value);
        assert_eq!(draw_axes(&value), (e.home, e.away), "{}", e.value);
    }
}

#[test]
fn axes_bulk_json_matches_for_all_1000_entries() {
    let entries = load("axes-bulk.json");
    assert_eq!(entries.len(), 1_000);
    for e in &entries {
        let value = hex32(&e.value);
        assert_eq!(axis(&value, AXIS_LABEL_HOME), e.home, "{}", e.value);
        assert_eq!(axis(&value, AXIS_LABEL_AWAY), e.away, "{}", e.value);
    }
}

#[test]
fn every_axis_is_a_permutation_and_home_never_equals_away() {
    // PROGRAM §6.2 domain separation: `home != away` is not guaranteed by the maths (one in
    // 10! per value), so a collision in 1,000 would point at the labels.
    for e in load("axes-bulk.json") {
        let (home, away) = draw_axes(&hex32(&e.value));
        assert!(
            is_permutation(&home) && is_permutation(&away),
            "{}",
            e.value
        );
        assert_ne!(home, away, "{}", e.value);
    }
}

#[test]
fn flipping_one_byte_of_the_value_changes_an_axis_in_at_least_990_of_1000() {
    // Audit focus: the shuffle depends on the whole value through sha256.
    let entries = load("axes-bulk.json");
    let mut changed = 0;
    for (i, e) in entries.iter().enumerate() {
        let value = hex32(&e.value);
        let mut flipped = value;
        flipped[i % 32] ^= 1 << (i % 8);
        if draw_axes(&flipped) != draw_axes(&value) {
            changed += 1;
        }
    }
    assert!(changed >= 990, "{changed} of 1000 changed");
}

#[test]
fn the_labels_and_the_cap_are_the_spec_values() {
    // PROGRAM §6.2 labels; §4.4 "capped at two".
    assert_eq!(AXIS_LABEL_HOME, b"home");
    assert_eq!(AXIS_LABEL_AWAY, b"away");
    assert_eq!(VAR_REPLACEMENTS_MAX, 2);
}
